"""empty message

Revision ID: 249ee4b1581f
Revises: 2a795b49142e
Create Date: 2025-12-05 13:35:20.799550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '249ee4b1581f'
down_revision = '2a795b49142e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('provider')
    with op.batch_alter_table('oauth_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('seller_user_id', sa.String(length=120), nullable=False))
        batch_op.drop_column('provider')
        batch_op.drop_column('provider_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_user_id', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('seller_user_id')
        batch_op.drop_column('seller')

    op.create_table('provider',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('service_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('contact_email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('provider_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('provider_pkey'))
    )
    op.drop_table('seller')
    # ### end Alembic commands ###
