"""empty message

Revision ID: ca04e4ab4e8e
Revises: 898253de26cb
Create Date: 2025-12-08 08:36:05.018090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca04e4ab4e8e'
down_revision = '898253de26cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_account', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['provider_user_id'])
        batch_op.create_unique_constraint(None, ['provider'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
