"""empty message

Revision ID: dcd348ce8eb3
Revises: ca04e4ab4e8e
Create Date: 2025-12-08 08:47:00.256041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd348ce8eb3'
down_revision = 'ca04e4ab4e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('diet_type', sa.String(length=50), nullable=True),
    sa.Column('meals_per_day', sa.Integer(), nullable=True),
    sa.Column('preferences', sa.String(length=250), nullable=True),
    sa.Column('adress', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_profile')
    # ### end Alembic commands ###
